version: '3.8'

services:
  app:
    build: .
    container_name: starwars_api_app
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8080
